apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: limited
spec:
  limits:
  - type: Container
    max:
      cpu: "250m" # Maximum CPU (0.25 core)
      memory: "128Mi" # Maximum Memory
    default:
      cpu: "100m" # Default CPU if not set
      memory: "64Mi" # Default Memory if not set
    defaultRequest:
      cpu: "100m" # Default CPU request if not set
      memory: "64Mi" # Default Memory request if not set
