apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: limited
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    requests.storage: "64Gi"
    persistentvolumeclaims: "10"
    pods: "5"
    services: "2"
    secrets: "2"
    configmaps: "2"